### ISSUE TITLE
AAL3 issue opening files 

### ISSUE THREAD

**Issue by DonatellaFracassi** [neurodebian/spm12#10]
Hello there, I'm new to the community. I operate from a 2015 Macbook Air using Matlab 2019a. I need to use the Automated Anatomical Labeling (AAL) toolbox in order to process some PET data. I downloaded the latest version (AAL3v1) from https://www.gin.cnrs.fr/en/tools/aal/ and then followed the instructions in 'AAL User guide' (https://www.gin.cnrs.fr/wp-content/uploads/AAL3_UserGuide_June2020.pdf) to install the software, which are: move zip to toolbox folder of spm, unzip, copy masks to the newly created atlas folder in spm. The toolbox is then available on the spm GUI's toolbox list but doesn't allow to select any of the data (previously normalized and smoothed PET data in .nii) and matlab gives a 'Dot indexing is not supported for variables of this type' error. This happens as well trying to open AAL3 directly from Matlab's command window or 'Results' section in sum GUI. Can anyone help? Thank you lots

**Comment by gllmflndn** [comment]
Hi @DonatellaFracassi Could you open this issue on the [GitHub SPM repository](https://github.com/spm/spm)? The repository here is dedicated to the packaging of SPM in NeuroDebian. If would help if you could copy the entire error message (that might contain information about in which function and at which line does the error occur).
